preload = /usr/share/backgrounds/archlinux/archbtw.png
preload = /usr/share/backgrounds/archlinux/archwave.png
preload = /usr/share/backgrounds/archlinux/archwaveinv.png
preload = /usr/share/backgrounds/archlinux/awesome.png
preload = /usr/share/backgrounds/archlinux/conference.png
preload = /usr/share/backgrounds/archlinux/geolanes.png
preload = /usr/share/backgrounds/archlinux/geowaves.png
preload = /usr/share/backgrounds/archlinux/gritty.png
preload = /usr/share/backgrounds/archlinux/landscape.jpg
preload = /usr/share/backgrounds/archlinux/lone.jpg
preload = /usr/share/backgrounds/archlinux/mountain.jpg
preload = /usr/share/backgrounds/archlinux/reflected.jpg
preload = /usr/share/backgrounds/archlinux/simple.png
preload = /usr/share/backgrounds/archlinux/small.png
preload = /usr/share/backgrounds/archlinux/snow.jpg
preload = /usr/share/backgrounds/archlinux/split.png
preload = /usr/share/backgrounds/archlinux/sunset.jpg
preload = /usr/share/backgrounds/archlinux/svalbard.jpg
preload = /usr/share/backgrounds/archlinux/wave.png
preload = /usr/share/backgrounds/archlinux/wild.png
preload = /usr/share/backgrounds/archlinux/wirefeather.png
preload = /usr/share/backgrounds/archlinux/wireparts.png
preload = ~/Pictures/wallpapers/wallpaper_msi_dark.png

wallpaper {
    monitor = DP-1
    path = /usr/share/backgrounds/archlinux/simple.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = ~/Pictures/wallpapers/wallpaper_msi_dark.png
    fit_mode = cover
}
