[env]
TERM = "xterm-256color"
SHELL = "/bin/zsh"

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 12

[shell]
program = "/bin/zsh"

[window]
opacity = 0.9
padding.x = 7
padding.y = 2
dimensions.columns = 132
dimensions.lines = 40
